library(dplyr)
paletteer_packages <- tibble::tribble(
  ~Name,                ~Github,                            ~github_ver,   ~CRAN, ~CRAN_ver,
  "awtools",            "awhstin/awtools",                  "0.2.1",       FALSE, NA,
  "basetheme",          "KKPMW/basetheme",                  "0.1.2",       TRUE,  "0.1.2",
  "beyonce",            "dill/beyonce",                     "0.1",         FALSE, NA,
  "calecopal",          "an-bui/calecopal",                 "0.1.0",       FALSE, NA,
  "cartography",        "riatelab/cartography",             "2.3.1.0",     TRUE,  "2.3.0",
  "colorblindr",        "clauswilke/colorblindr",           "0.1.0",       FALSE, NA,
  "colRoz",             "jacintak/colRoz",                  "0.2.2",       FALSE, NA,
  "dichromat",          NA,                                 NA,            TRUE,  "2.0-0",
  "DresdenColor",       "katiesaund/DresdenColor",          "0.0.0.9000",  FALSE, NA,
  "dutchmasters",       "EdwinTh/dutchmasters",             "0.1.0",       FALSE, NA,
  "fishualize",         "nschiett/fishualize",              "0.2.0",     TRUE,  "0.2.0",
  "futurevisions",      "JoeyStanley/futurevisions",        "0.1.0",       FALSE, NA,
  "gameofthrones",      "aljrico/gameofthrones",            "1.0.2",       TRUE,  "1.0.2",
  "ggpomological",      "gadenbuie/ggpomological",          "0.1.2",       FALSE, NA,
  "ggsci",              "road2stat/ggsci",                  "2.9",         TRUE,  "2.9",
  "ggthemes",           "jrnold/ggthemes",                  "4.2.0",       TRUE,  "4.2.0",
  "ggthemr",            "cttobin/ggthemr",                  "1.1.0",       FALSE, NA,
  "ghibli",             "ewenme/ghibli",                    "0.3.1.9000",  TRUE,  "0.3.1",
  "grDevices",          NA,                                 NA,            TRUE,  "2.0-14",
  "harrypotter",        "aljrico/harrypotter",              "2.1.1",       TRUE,  "2.1.1",
  "IslamicArt",         "lambdamoses/IslamicArt",           "0.1.0",       FALSE, NA,
  "khroma",             "nfrerebeau/khroma",                "1.3.0.9000",  TRUE,  "1.3.0",
  "jcolors",            "jaredhuling/jcolors",              "0.0.4",       TRUE,  "0.0.4",
  "LaCroixColoR",       "johannesbjork/LaCroixColoR",       "0.1.0",       FALSE, NA,
  "lisa",               "tyluRp/lisa",                      "0.1.1.9000",  TRUE,  "0.1.1",
  "MapPalettes",        "disarm-platform/MapPalettes",      "0.0.2",       FALSE, NA,
  "miscpalettes",       "EmilHvitfeldt/miscpalettes",       "0.0.0.9000",  FALSE, NA,
  "nationalparkcolors", "katiejolly/nationalparkcolors",    "0.1.0",       FALSE, NA,
  "NineteenEightyR",    "m-clark/NineteenEightyR",          "0.1.0",       FALSE, NA,
  "nord",               "jkaupp/nord",                      "1.0.0",       TRUE,  "1.0.0",
  "ochRe",              "ropenscilabs/ochRe",               "1.0.0",       FALSE, NA,
  "oompaBase",          NA,                                 NA,            TRUE,  "3.2.9",
  "palettesForR",       "frareb/palettesForR",              "0.1.2",       TRUE,  "0.1.2",
  "palettetown",        "timcdlucas/palettetown",           "0.1.1.90000", TRUE,  "0.1.1",
  "palr",               "AustralianAntarcticDivision/palr", "0.2.0",       TRUE,  "0.2.0",
  "pals",               "kwstat/pals",                      "1.6",         TRUE,  "1.6",
  "PNWColors",          "jakelawlor/PNWColors",             "0.1.0",       FALSE, NA,
  "Polychrome",         NA,                                 NA,            TRUE,  "1.2.4",
  "rcartocolor",        "Nowosad/rcartocolor",              "2.0.0",       TRUE,  "2.0.0",
  "RColorBrewer",       NA,                                 NA,            TRUE,  "1.1-2",
  "Redmonder",          NA,                                 NA,            TRUE,  "0.2.0",
  "RSkittleBrewer",     "alyssafrazee/RSkittleBrewer",      "1.1",         FALSE, NA,
  "scico",              "thomasp85/scico",                  "1.1.0",       TRUE,  "1.1.0",
  "suffrager",          "alburezg/suffrage",                "0.1.0",       FALSE, NA,
  "tidyquant",          "business-science/tidyquant",       "1.0.0",       TRUE,  "1.0.0",
  "trekcolors",         "leonawicz/trekcolors",             "0.1.2",       TRUE,  "0.1.1",
  "tvthemes",           "Ryo-N7/tvthemes",                  "1.1.0",       TRUE,  "1.1.0",
  "unikn",              "hneth/unikn",                      "0.2.0.9003",  TRUE,  "0.2.0",
  "vapeplot",           "seasmith/vapeplot",                "0.1.0",       FALSE, NA,
  "vapoRwave",          "moldach/vapoRwave",                "0.0.0.9000",  FALSE, NA,
  "viridis",            "sjmgarnier/viridis",               "0.5.1",       TRUE,  "0.5.1",
  "visibly",            "m-clark/visibly",                  "0.2.7",       FALSE, NA,
  "werpals",            "sciencificity/werpals",            "0.1.0",       FALSE, NA,
  "wesanderson",        "karthik/wesanderson",              "0.3.6.9000",  TRUE,  "0.3.6",
  "yarrr",              "ndphillips/yarrr",                 "0.1.6",       TRUE,  "0.1.5"
) %>%
  arrange(Name)

usethis::use_data(paletteer_packages, overwrite = TRUE)
