library(dplyr)
paletteer_packages <- tibble::tribble(
  ~Name                  , ~Github                            , ~github_ver   , ~CRAN , ~CRAN_ver ,
  "awtools"              , "awhstin/awtools"                  , "0.2.1"       , FALSE , NA        ,
  "basetheme"            , "karoliskoncevicius/basetheme"     , "0.1.3"       , TRUE  , "0.1.3"   ,
  "beyonce"              , "dill/beyonce"                     , "0.1"         , FALSE , NA        ,
  "ButterflyColors"      , "junqueiragaabi/ButterflyColors"   , "0.0.0.9000"  , FALSE , NA        ,
  "calecopal"            , "an-bui/calecopal"                 , "0.1.0"       , FALSE , NA        ,
  "cartography"          , "riatelab/cartography"             , "3.1.5"       , TRUE  , "3.1.5"   ,
  "colorBlindness"       , NA                                 , NA            , TRUE  , "0.1.9"   ,
  "colorblindr"          , "clauswilke/colorblindr"           , "0.1.0"       , FALSE , NA        ,
  "colRoz"               , "jacintak/colRoz"                  , "0.2.2"       , FALSE , NA        ,
  "dichromat"            , NA                                 , NA            , TRUE  , "2.0-0.1" ,
  "DresdenColor"         , "katiesaund/DresdenColor"          , "0.0.0.9000"  , FALSE , NA        ,
  "dutchmasters"         , "EdwinTh/dutchmasters"             , "0.1.0"       , FALSE , NA        ,
  "feathers"             , "shandiya/feathers"                , "0.0.0.9000"  , FALSE , NA        ,
  "fishualize"           , "nschiett/fishualize"              , "0.2.3"       , TRUE  , "0.2.3"   ,
  "futurevisions"        , "JoeyStanley/futurevisions"        , "0.1.1"       , FALSE , NA        ,
  # "gameofthrones",      "aljrico/gameofthrones",            "1.0.2",       TRUE,  "1.0.2",
  "ggpomological"        , "gadenbuie/ggpomological"          , "0.1.2"       , FALSE , NA        ,
  "ggprism"              , "csdaw/ggprism"                    , "1.0.7.9000"  , TRUE  , "1.0.7"   ,
  "ggsci"                , "nanxstats/ggsci"                  , "4.2.0"       , TRUE  , "4.2.0"   ,
  "ggthemes"             , "jrnold/ggthemes"                  , "5.2.0"       , TRUE  , "5.2.0"   ,
  "ggthemr"              , "Mikata-Project/ggthemr"           , "1.1.0"       , FALSE , NA        ,
  "ghibli"               , "ewenme/ghibli"                    , "0.3.4"       , TRUE  , "0.3.4"   ,
  "grDevices"            , NA                                 , NA            , TRUE  , "4.5.2"   ,
  "harrypotter"          , "aljrico/harrypotter"              , "2.1.1"       , TRUE  , "2.1.1"   ,
  "IslamicArt"           , "lambdamoses/IslamicArt"           , "0.1.0"       , FALSE , NA        ,
  "impressionist.colors" , NA                                 , NA            , TRUE  , "1.0"     ,
  "jcolors"              , "jaredhuling/jcolors"              , "0.0.5"       , FALSE , NA        ,
  "khroma"               , "tesselle/khroma"                  , "1.17.0.9000" , TRUE  , "1.17.0"  ,
  "LaCroixColoR"         , "johannesbjork/LaCroixColoR"       , "0.1.0"       , FALSE , NA        ,
  "lisa"                 , "tylerlittlefield/lisa"            , "0.1.2.9000"  , TRUE  , "0.1.2"   ,
  "ltc"                  , "loukesio/ltc_palettes"            , "0.2.0"       , FALSE , NA        ,
  "MetBrewer"            , "BlakeRMills/MetBrewer"            , "0.3.0"       , TRUE  , "0.2.0"   ,
  "MexBrewer"            , "paezha/MexBrewer"                 , "0.0.2"       , FALSE , "0.0.2"   ,
  "Manu"                 , "G-Thomson/Manu"                   , "0.0.2"       , FALSE , NA        ,
  "MapPalettes"          , "disarm-platform/MapPalettes"      , "0.0.2"       , FALSE , NA        ,
  "musculusColors"       , "dawnbarlow/musculusColors"        , "0.1.0"       , FALSE , NA        ,
  "miscpalettes"         , "EmilHvitfeldt/miscpalettes"       , "0.0.0.9000"  , FALSE , NA        ,
  "MoMAColors"           , "BlakeRMills/MoMAColors"           , "0.0.0.9000"  , FALSE , NA        ,
  "nationalparkcolors"   , "katiejolly/nationalparkcolors"    , "0.1.0"       , FALSE , NA        ,
  "NatParksPalettes"     , "kevinsblake/NatParksPalettes"     , "0.2.0"       , TRUE  , "0.2.0"   ,
  "nbapalettes"          , "murrayjw/nbapalettes"             , "0.1.0.9000"  , TRUE  , "0.1.0"   ,
  "NineteenEightyR"      , "m-clark/NineteenEightyR"          , "0.1.0"       , FALSE , NA        ,
  "nord"                 , "jkaupp/nord"                      , "1.0.0"       , TRUE  , "1.0.0"   ,
  "ochRe"                , "hollylkirk/ochRe"                 , "1.0.0"       , FALSE , NA        ,
  "oompaBase"            , NA                                 , NA            , TRUE  , "3.2.10"  ,
  "palettesForR"         , "frareb/palettesForR"              , "0.1.2"       , TRUE  , "0.1.2"   ,
  "palettetown"          , "timcdlucas/palettetown"           , "0.1.1.90000" , TRUE  , "0.1.1"   ,
  "palr"                 , "AustralianAntarcticDivision/palr" , "0.4.0"       , TRUE  , "0.4.0"   ,
  "pals"                 , "kwstat/pals"                      , "1.10"        , TRUE  , "1.10"    ,
  "peRReo"               , "jbgb13/peRReo"                    , "0.1.0"       , FALSE , NA        ,
  "PNWColors"            , "jakelawlor/PNWColors"             , "0.1.0"       , FALSE , NA        ,
  "Polychrome"           , NA                                 , NA            , TRUE  , "1.5.4"   ,
  "popthemes"            , "johnmackintosh/popthemes"         , "0.0.0.9000"  , FALSE , NA        ,
  "PrettyCols"           , "nrennie/PrettyCols"               , "1.1.0.9003"  , TRUE  , "1.1.0"   ,
  "rcartocolor"          , "Nowosad/rcartocolor"              , "2.1.2"       , TRUE  , "2.1.2"   ,
  "RColorBrewer"         , NA                                 , NA            , TRUE  , "1.1.3"   ,
  "Redmonder"            , "pmdci/redmonder"                  , "0.2.0"       , TRUE  , "0.2.0"   ,
  "rockthemes"           , "johnmackintosh/rockthemes"        , "0.0.0.9000"  , FALSE , NA        ,
  "RSkittleBrewer"       , "alyssafrazee/RSkittleBrewer"      , "1.1"         , FALSE , NA        ,
  "rtist"                , "tomasokal/rtist"                  , "1.0.0"       , TRUE  , "1.0.0"   ,
  "scico"                , "thomasp85/scico"                  , "1.5.0.9000"  , TRUE  , "1.5.0"   ,
  "severance"            , "ivelasq/severance"                , "0.0.0.9000"  , FALSE , NA        ,
  "soilpalettes"         , "kaizadp/soilpalettes"             , "0.1.0"       , FALSE , NA        ,
  "suffrager"            , "alburezg/suffrager"               , "0.1.0"       , FALSE , NA        ,
  "tayloRswift"          , "asteves/tayloRswift"              , "0.3.0"       , FALSE , NA        ,
  "tidyquant"            , "business-science/tidyquant"       , "1.0.11.9000" , TRUE  , "1.0.11"  ,
  "trekcolors"           , "leonawicz/trekcolors"             , "0.2.0"       , TRUE  , "0.2.0"   ,
  "tvthemes"             , "Ryo-N7/tvthemes"                  , "1.3.3"       , TRUE  , "1.3.3"   ,
  "unikn"                , "hneth/unikn"                      , "1.0.0.9004"  , TRUE  , "1.0.0"   ,
  "vangogh"              , "cherylisabella/vangogh"           , "0.1.3"       , TRUE  , "0.1.3"   ,
  "vapeplot"             , "seasmith/vapeplot"                , "0.1.0"       , FALSE , NA        ,
  "vapoRwave"            , "moldach/vapoRwave"                , "0.3.0"       , FALSE , NA        ,
  "viridis"              , "sjmgarnier/viridis"               , "0.6.5"       , TRUE  , "0.6.5"   ,
  "visibly"              , "m-clark/visibly"                  , "0.2.9"       , FALSE , NA        ,
  "waRhol"               , "alexskeels/waRhol"                , "0.1.0"       , FALSE , NA        ,
  "werpals"              , "sciencificity/werpals"            , "0.1.0"       , FALSE , NA        ,
  "wesanderson"          , "karthik/wesanderson"              , "0.3.7"       , TRUE  , "0.3.7"   ,
  "yarrr"                , "ndphillips/yarrr"                 , "0.1.14"      , TRUE  , NA
) |>
  arrange(Name)

readr::write_csv(paletteer_packages, "data-raw/paletteer_packages.csv")
usethis::use_data(paletteer_packages, overwrite = TRUE)
