library(dplyr)
paletteer_packages <- tibble::tribble(
  ~Name,           ~Github,                ~github_ver, ~CRAN, ~CRAN_ver,
  "awtools",       "awhstin/awtools",         "0.2.1",   FALSE, NA,
  "cartography",   "riatelab/cartography",    "2.2.1.1", TRUE,  "2.2.1",
  "dichromat",     NA,                        NA,        TRUE,  "2.0-0",
  "dutchmasters",  "EdwinTh/dutchmasters",    "0.1.0",   FALSE, NA,
  "gameofthrones", "aljrico/gameofthrones",    "1.0.1",   TRUE,  "1.0.0",
  "ggsci",         "road2stat/ggsci",         "2.9",     TRUE,  "2.9",
  "ggpomological", "gadenbuie/ggpomological", "0.1.2",   FALSE, NA,
  "ggthemes",      "jrnold/ggthemes",         "4.2.0",   TRUE,  "4.2.0",
  "ghibli",        "ewenme/ghibli",           "0.3.0.9000", TRUE, "0.3.0",
  "grDevices", NA, NA, TRUE, "2.0-14",
  "harrypotter", "aljrico/harrypotter", "2.1.0", TRUE, "2.1.0",
  "jcolors", "jaredhuling/jcolors", "0.0.4", TRUE, "0.0.4",
  "LaCroixColoR", "johannesbjork/LaCroixColoR", "0.1.0", FALSE, NA,
  "NineteenEightyR", "m-clark/NineteenEightyR", "0.1.0", FALSE, NA,
  "nord", "jkaupp/nord", "1.0.0", TRUE, "1.0.0",
  "oompaBase", NA, NA, TRUE, "3.2.9",
  "ochRe", "ropenscilabs/ochRe", "1.0.0", FALSE, NA,
  "palettetown", "timcdlucas/palettetown", "0.1.1.90000", TRUE, "0.1.1",
  "palr", "AustralianAntarcticDivision/palr", "0.1.0", TRUE, "0.1.0",
  "pals", "kwstat/pals", "1.6", TRUE, "1.6",
  "Polychrome", NA, NA, TRUE, "1.2.3",
  "miscpalettes", "EmilHvitfeldt/miscpalettes", "0.0.0.9000", FALSE, NA,
  "rcartocolor", "Nowosad/rcartocolor", "2.0.0", TRUE, "2.0.0",
  "RColorBrewer", NA, NA, TRUE, "1.1-2",
  "Redmonder", NA, NA, TRUE, "0.2.0",
  "RSkittleBrewer", "alyssafrazee/RSkittleBrewer", "1.1", FALSE, NA,
  "scico", "thomasp85/scico", "1.1.0", TRUE, "1.1.0",
  "tidyquant", "business-science/tidyquant", "0.5.8", TRUE, "0.5.8",
  "viridis", "sjmgarnier/viridis", "0.5.1", TRUE, "0.5.1",
  "visibly", "m-clark/visibly", "0.2.6", FALSE, NA,
  "vapoRwave", "moldach/vapoRwave", "0.0.0.9000", FALSE, NA,
  "wesanderson", "karthik/wesanderson", "0.3.6.9000", TRUE, "0.3.6",
  "yarrr", "ndphillips/yarrr", "0.1.6", TRUE, "0.1.5",
  "lisa", "tyluRp/lisa", "0.1.1.9000", TRUE, "0.1.1",
  "IslamicArt", "lambdamoses/IslamicArt", "0.1.0", FALSE, NA,
  "basetheme", "KKPMW/basetheme", "0.1.2", TRUE, "0.1.2",
  "vapeplot", "seasmith/vapeplot", "0.1.0", FALSE, NA,
  "ggthemr", "cttobin/ggthemr", "1.1.0", FALSE, NA,
  "fishualize", "nschiett/fishualize", "0.2.999", TRUE, "0.1.0",
  "DresdenColor", "katiesaund/DresdenColor", "0.0.0.9000", FALSE, NA,
  "trekcolors", "leonawicz/trekcolors", "0.1.2", TRUE, "0.1.1",
  "nationalparkcolors", "katiejolly/nationalparkcolors", "0.1.0", FALSE, NA,
  "MapPalettes", "disarm-platform/MapPalettes", "0.0.2", FALSE, NA,
  "werpals", "sciencificity/werpals", "0.1.0", FALSE, NA,
  "calecopal", "an-bui/calecopal", "0.1.0", FALSE, NA,
  "colorblindr", "clauswilke/colorblindr", "0.1.0", FALSE, NA,
  "colRoz", "jacintak/colRoz", "0.2.2", FALSE, NA
) %>%
  arrange(Name)

usethis::use_data(paletteer_packages, overwrite = TRUE)
